### ISSUE TITLE
Handle duplicates in multiple meshes while repacking?

### ISSUE THREAD

**Issue by fire** [jpcy/xatlas#24]
The current duplication removal only handles reused material indexes in the same mesh, is it possible to extend this for multiple meshes when merging and repacking textures?

**Comment by fire** [comment]
I tried making a merge uvs options to packing, but I couldn't get it to work.

**Comment by fire** [comment]
The index map gets difficult to calculate when you merge the meshes. Try to keep them separate.

**Comment by fire** [comment]
Got it to work.

**Comment by fire** [comment]
The repacked meshes on different uvmeshes still need a way to ensure they're the same.

**Comment by saml1er** [comment]
> I tried making a merge uvs options to packing, but I couldn't get it to work.

> The repacked materials on different uvmeshes still need a way to ensure they're the
 same.

What are you trying to accomplish? I'm not sure if this is what you want, but I have [some code](https://github.com/multitheftauto/mtasa-blue/blob/fc2fe14de3f7e01dc477dff2c675bfab0c3b5e84/Client/core/C3DModelOptimizer.cpp#L84) which loops through meshes of a model and maps each vertex to a material on a single vector container.

This is how I get the material index back for the mesh vertex from that container: https://github.com/multitheftauto/mtasa-blue/blob/fc2fe14de3f7e01dc477dff2c675bfab0c3b5e84/Client/core/C3DModelOptimizer.cpp#L527

Since you mentioned that you are "merging" them, I'm guessing that you are calling `xatlas::AddUvMesh` once for the model. If that's the case, the idea is still the same, you can access the material index for a mesh from the merged meshes the same way.

**Comment by fire** [comment]
![bake](https://user-images.githubusercontent.com/32321/61333906-45abaa80-a7dd-11e9-9343-cc62103f7f09.png)

Here's an example of the bug.

**Comment by fire** [comment]
![room_editor_baked](https://user-images.githubusercontent.com/32321/61335885-edc47200-a7e3-11e9-8b4b-3e6aedc82e76.png)
![room_editor_original](https://user-images.githubusercontent.com/32321/61335886-ee5d0880-a7e3-11e9-90c5-4377d61bcbfc.png)

Original vs Baked.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/61340141-e6a65f80-a7f5-11e9-91af-6161064df563.png)

**Comment by jpcy** [comment]
It's not really a bug, this library deals with **unique** parameterizations.

The UvMesh chart detection looks for connected faces in UV space, which is fine for unique parameterizations. But faces that aren't connected in worldspace and have overlapping or duplicate edges in UV space (i.e. not unique) will be detected as belonging to the same chart. That happens to be what you want, but only by coincidence.

Charts are per-mesh, so if you want that behavior for the whole atlas, merge all mesh geometry so you're only adding a single mesh.

**Comment by fire** [comment]
Won't overlapping UVs for the same mesh be a problem? There's also the problem linking the specific uv to a unique material when we merge the mesh first.

Is it possible to have the consistent material to vertex mappings over an array of ids?

For example:

Mesh 0:

* index 0 goes to material idx 0
* index 1 goes to material idx 0
* index 2 goes to material idx 0

Mesh 1:

* index 0 goes to material idx 1
* index 1 goes to material idx 1
* index 2 goes to material idx 1

You're suggesting I do this.

* index 0 goes to material idx 0
* index 1 goes to material idx 0
* index 2 goes to material idx 0
* index 3 goes to material idx 1
* index 4 goes to material idx 1
* index 5 goes to material idx 1

I'll try it.

**Comment by saml1er** [comment]
@fire Why don't you just ignore the materials which take up too much space in the atlas? It might result in one extra draw call, but you'll save memory.
