### ISSUE TITLE
AddMesh() stack overflow.

### ISSUE THREAD

**Issue by ArionTT** [jpcy/xatlas#27]
What is MAX_SIZE of xatlas?
I try add my whole scene to xatlas to build Atlas. My scene mesh object count is 222. Is it greater than xatlas size?

my call:
`
		xatlas::SetPrint(Print, s_verbose);
		m_atlas = xatlas::Create();

		// Set progress callback.
		Stopwatch stopwatch;
		xatlas::SetProgressCallback(m_atlas, ProgressCallback, &stopwatch);

		xatlas::MeshDecl meshDecl;
		meshDecl.vertexCount = _tran->m_mesh->n_vertices;
		meshDecl.vertexPositionData = &position.data()[0].data[0];
		meshDecl.vertexPositionStride = sizeof(UVVec3);
		meshDecl.indexCount = (uint32_t)indices.size();
		meshDecl.indexData = indices.data();
		meshDecl.indexFormat = xatlas::IndexFormat::UInt32;
		xatlas::AddMeshError::Enum error = xatlas::AddMesh(m_atlas, meshDecl);
		if (error != xatlas::AddMeshError::Success)
		{
			xatlas::Destroy(m_atlas);
			printf("\rError adding mesh %s \n", xatlas::StringForEnum(error));
			return;
		}

		xatlas::AddMeshJoin(m_atlas);

                xatlas::Generate(m_atlas);
`

**Comment by jpcy** [comment]
There's no explicit limit on meshes. The [Godot tps demo](https://github.com/godotengine/tps-demo) works for me, and that has 575 objects/meshes, 2.5 million triangles and 7 million vertices.

Large meshes will probably need a 64-bit build since memory usage can be higher than 4GB. But running out of memory would crash with an access violation (exit code -1073741819/0xC0000005), not a stack overflow.

**Comment by jpcy** [comment]
Probably fixed in #38.
