### ISSUE TITLE
Atlas crash because of a recent commit

### ISSUE THREAD

**Issue by saml1er** [jpcy/xatlas#32]
Caused by dc04de3c8ba63d17be6a7a831c81ba991fb8143c. Use this to reproduce: [lodferryland.zip](https://github.com/jpcy/xatlas/files/3462415/lodferryland.zip)

`example_repack.exe clump_output.obj`

**Comment by jpcy** [comment]
That's because I changed the default `PackOptions::maxChartSize` to 0 (infinite) in that commit. There's some very large charts in that model that are too big to fit into memory. Look at some of the uvs like `vt 23372.2 -1.21143`. To fix the issue, you could change `PackOptions::maxChartSize` to whatever limit you want, or edit the model uvs.

**Comment by saml1er** [comment]
>
> To fix the issue, you could change PackOptions::maxChartSize to whatever limit you want, or edit the model uvs.

I see. That is interesting. Thank you!
