### ISSUE TITLE
some error about example

### ISSUE THREAD

**Issue by SuRuiMeng** [jpcy/xatlas#66]
when i load a obj model，is a simple cube. I get a error `Assertion failed: m_id != 0xffffffffui32 || (m_id == 0xffffffffui32 && result == 0xffffffffui32), file D:\project\xatlas\xatlas.cpp, line 2750`,How did this error arise? and how am I going to fix it?

thinks

[model.zip](https://github.com/jpcy/xatlas/files/4850257/model.zip)

**Comment by SuRuiMeng** [comment]
did i need `objzero` library?

**Comment by jpcy** [comment]
Try latest, that was fixed in [87faf58f6e15072cffec88e2132a233259533432](https://github.com/jpcy/xatlas/commit/87faf58f6e15072cffec88e2132a233259533432).

I recommend switching to Release build. Debug (the Visual Studio default) is slow.

You can use whatever obj library you like. The examples use an old version of tinyobjloader, while the viewer uses objzero.

**Comment by SuRuiMeng** [comment]
thinks for you reply，I will to try the new vesion.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jonathan&amp;nbsp;Young&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月30日(星期二) 晚上6:50
收件人:&nbsp;&quot;jpcy/xatlas&quot;<xatlas@noreply.github.com&gt;;
抄送:&nbsp;&quot;苏瑞梦&quot;<934274351@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jpcy/xatlas] some error about example (#66)
