### ISSUE TITLE
how can I get a new texcoord

### ISSUE THREAD

**Issue by yongweixie** [jpcy/xatlas#76]
![Snipaste_2020-09-02_10-53-55](https://user-images.githubusercontent.com/20678114/91926834-b88e2280-ed0a-11ea-9f6d-b0d29e4f99b5.png)
how can i get the result above?
i just get a result like this.

**Comment by yongweixie** [comment]
![Snipaste_2020-09-03_10-58-23](https://user-images.githubusercontent.com/20678114/92066424-6addec80-edd4-11ea-8bfa-b47125e8f5fc.png)

**Comment by jpcy** [comment]
example_uvmesh packs 10 copies of the same model, that's why you can see the same charts duplicated 10 times.

If you mean copying texture data from the old texture coordinates to the new ones, there was an example that showed how to do that (search "repack" in the commit log). It didn't quite work correctly, and I didn't want to fix and maintain it since it was outside the scope of this library, so I removed it.

**Comment by yongweixie** [comment]
> example_uvmesh packs 10 copies of the same model, that's why you can see the same charts duplicated 10 times.
> 
> If you mean copying texture data from the old texture coordinates to the new ones, there was an example that showed how to do that (search "repack" in the commit log). It didn't quite work correctly, and I didn't want to fix and maintain it since it was outside the scope of this library, so I removed it.

I find it ,thank you very much.
