### ISSUE TITLE
xatlas packs into 0-1 space only

### ISSUE THREAD

**Issue by Ben-Mack** [jpcy/xatlas#83]
Sometimes, especially when there's a lot of objects, the UV is packed into a non-squared area. 
How can I tell xatlas to only pack into 0-1 area, so I can bake everything in 1 lightmap?

This is my current result chart:
![example_charts00](https://user-images.githubusercontent.com/6309393/97969923-4d88c700-1df3-11eb-89b1-68858cc52102.jpg)

**Comment by jpcy** [comment]
This is most likely caused by some geometry with a high aspect ratio, i.e. you end up with a long, thin chart. When packed, the chart resizes the atlas to a nowhere-near-square aspect ratio. [This gltf sample model has the same problem.](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy)

The solution is to set `xatlas::PackOptions::maxChartSize` to scale down charts larger than the maximum. Set it to whatever you want the atlas dimensions to be. E.g. with the Buggy model, setting it to 1024 gives a roughly 1024x1024 atlas, instead of the default settings, which gives 11915x134, because the offending chart is 11915 texels wide.

**Comment by Ben-Mack** [comment]
Thank you, `maxChartSize` fixed it for me. So I guess I should always set `resolution` and `maxChartSize` to the same value to avoid this problem.

**Comment by Ben-Mack** [comment]
@jpcy Set `maxChartSize` equal to `resolution` works well in non brute force mode. But whenever I turn on `Brute force`, it always packed into a non square atlas. 
The result is great but there're so much wasted blank space. In most case, textures are required to be power of two, so atlas has to be packed in a square aspect ratio to maximizing utilization.

Do you have any idea on this one? Maybe like adding a flag to force packing into a square area?

Brute force ON
![image](https://user-images.githubusercontent.com/6309393/100208760-aa335980-2f3b-11eb-8061-0bcc4abec84a.png)


Brute force off
![image](https://user-images.githubusercontent.com/6309393/100210845-04351e80-2f3e-11eb-83ff-34e71a64e5fe.png)

**Comment by jpcy** [comment]
That is a side effect of the main performance optimization for brute force packing. Charts are divided into buckets based on area and packed largest first. The current pack position is used as a starting point for the next chart, until the bucket changes, then it resets to (0, 0). Unless charts are evenly distributed in size, the atlas will be be taller than it is wide. Without this optimization, brute force packing is slow to the point of being unusable.

Power of two texture doesn't mean width and height have to be same. In that brute force pack you could lower texels per unit a little to fit in a 1024x2048 texture.

**Comment by Ben-Mack** [comment]
Thank you for your detailed reply! I'm fine with non bruteforce mode as long as it still be squared :)
